type SeasoningEffectCategory =
  | "REDUCE_BITE_TIME_PERCENT"
  | "BOOST_RARITY_BUCKET"
  | "INCREASE_SHINY_CHANCE_MULTIPLIER"
  | "BOOST_POKEMON_LEVEL"
  | "BOOST_FRIENDSHIP"
  | "DROPS_REROLL_COUNT"
  | "NO_EFFECT"

  // IVs
  | "BOOST_HP_IVS"
  | "BOOST_ATTACK_IVS"
  | "BOOST_DEFENSE_IVS"
  | "BOOST_SPECIAL_ATTACK_IVS"
  | "BOOST_SPECIAL_DEFENSE_IVS"
  | "BOOST_SPEED_IVS"

  // Reeling & Ability
  | "INCREASE_REEL_CHANCE"
  | "ATTRACT_HIDDEN_ABILITY"
  | "ATTRACT_FEMALE_POKEMON"
  | "ATTRACT_MALE_POKEMON"

  // EV Yields
  | "ATTRACT_HP_EV_YIELD"
  | "ATTRACT_ATTACK_EV_YIELD"
  | "ATTRACT_DEFENSE_EV_YIELD"
  | "ATTRACT_SPECIAL_ATTACK_EV_YIELD"
  | "ATTRACT_SPECIAL_DEFENSE_EV_YIELD"
  | "ATTRACT_SPEED_EV_YIELD"

  // Natures
  | "ATTRACT_ATTACK_NATURE"
  | "ATTRACT_DEFENSE_NATURE"
  | "ATTRACT_SPECIAL_ATTACK_NATURE"
  | "ATTRACT_SPECIAL_DEFENSE_NATURE"
  | "ATTRACT_SPEED_NATURE"

  // Egg Groups (BOOST_EGG_GROUP_...)
  | "BOOST_EGG_GROUP_DRAGON"
  | "BOOST_EGG_GROUP_MONSTER"
  | "BOOST_EGG_GROUP_WATER_3"
  | "BOOST_EGG_GROUP_BUG"
  | "BOOST_EGG_GROUP_FAIRY"
  | "BOOST_EGG_GROUP_GRASS"
  | "BOOST_EGG_GROUP_HUMAN_LIKE"
  | "BOOST_EGG_GROUP_FLYING"
  | "BOOST_EGG_GROUP_FIELD"
  | "BOOST_EGG_GROUP_WATER_1"
  | "BOOST_EGG_GROUP_WATER_2"
  | "BOOST_EGG_GROUP_MINERAL"
  | "BOOST_EGG_GROUP_AMORPHOUS"

  // Types (BOOST_TYPE_...)
  | "BOOST_TYPE_BUG"
  | "BOOST_TYPE_DARK"
  | "BOOST_TYPE_DRAGON"
  | "BOOST_TYPE_GRASS"
  | "BOOST_TYPE_ELECTRIC"
  | "BOOST_TYPE_FAIRY"
  | "BOOST_TYPE_FIGHTING"
  | "BOOST_TYPE_FIRE"
  | "BOOST_TYPE_FLYING"
  | "BOOST_TYPE_GHOST"
  | "BOOST_TYPE_GROUND"
  | "BOOST_TYPE_ICE"
  | "BOOST_TYPE_NORMAL"
  | "BOOST_TYPE_POISON"
  | "BOOST_TYPE_PSYCHIC"
  | "BOOST_TYPE_ROCK"
  | "BOOST_TYPE_STEEL"
  | "BOOST_TYPE_WATER";

export type SeasoningEffect = {
  category: SeasoningEffectCategory;
  value: string | null;
};

export type SeasoningItem = {
  item_name: string;
  effects: SeasoningEffect[];
};
